pipeline {
    agent any
    environment {
        PATH = "/opt/node/v14.21.3/bin:$PATH"
        SONAR_TOKEN = "7f4111312189c94963ecd73b1d1d9050d111601f"
    }
    stages {
        stage('dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('sonarscanning') {
            steps {
                script {
                    // Execute SonarScanner
                    sh '''
                    sonar-scanner \
                        -Dsonar.organization=marionngwa \
                        -Dsonar.projectKey=Marionngwa_nodejs \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=https://sonarcloud.io \
                        -Dsonar.login=${env.SONAR_TOKEN}
                    '''
                }
            }
        }
        
        stage('start the app') {
            steps {
                sh 'npm pack'
            }
        }
        
        stage('upload artifact') {
            steps {
                sh 'curl -uadmin:AP6APkHxetchhfhHqpaawMctMhu -T my-app-1.2.0.tgz "http://ec2-54-197-98-251.compute-1.amazonaws.com:8081/artifactory/example-repo-local/nodejsapp"'
            }
        }
    }
}
