pipeline {
    agent any
    environment {
        PATH = "/usr/bin:${env.PATH}"
    }
    stages {
        stage('dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('start the app'){
            steps {
                sh 'npm package'
            }
        }
        
    }
}
