pipeline {
    agent any
    environment {
        PATH = "/usr/bin:${env.PATH}"
    }
    stages {
        stage('dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('building the code') {
            steps {
                sh 'npm start'
            }
        }

    }
}
