pipeline {
    agent any

    tools {
        nodejs 'nodejs'
        // Define Java 8 installation
        jdk 'java8'
    }

    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'npm install'
                }
            }
        }
        stage('SonarQube Analysis') {
            environment {
                // Define SonarQube properties
                SONAR_TOKEN = credentials('sonar-token')  
            }
            steps {
                script {
                    // Use Java 8 for SonarQube analysis
                    sh '''
                        export PATH="${JAVA_HOME}/bin:${PATH}"
                        /opt/sonar-scanner/bin/sonar-scanner -X \
                        -Dsonar.organization=marionngwa \
                        -Dsonar.projectKey=Marionngwa_nodejs \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=https://sonarcloud.io \
                        -Dsonar.login=${SONAR_TOKEN}
                    '''
                }
            }
        }
    }
}
