pipeline {
    agent any

    tools {
        nodejs 'nodejs'
        
    }

    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'npm install'
                }
            }
        }
        stage('SonarQube Analysis') {
            environment {
                // Define SonarQube properties
                SONAR_TOKEN = credentials('sonar-token')  
            }
            steps {
                script {
                    def scannerHome = tool 'sonar-scanner'
                    def scannerCmd = "${scannerHome}/bin/sonar-scanner"
                    sh "${scannerCmd} -Dsonar.organization=marionngwa -Dsonar.projectKey=Marionngwa_nodejs -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN}"
                }
            }
        }
    }
}
