pipeline{
    agent{
        label 'ubuntu-server'
    }

    stages{
        stage('Run nodejs container'){
            agent{
                docker{
                    image 'node:14'
                    args 'root:root'
                }
            }
            steps{
                sh 'npm install'
            }
        }
    }
}