pipeline{
    agent{
        docker{
            image 'node:14'
            args '-u root:root'
        }
    }
    stages{
        stage('Dependencies'){
            steps{
                sh 'npm install'
            }
        }

        stage('package'){
            steps{
                sh 'npm pack'
            }
        }

    }
}